### ISSUE TITLE
I am ready to bring my wealth of knowledge and technical skills to your team and support your mission with dedication and innovation.

### ISSUE THREAD

**Issue by kentaurse** [AutoLabz/AutoLabzLandingUI#1]
Greetings, I'm Ethan Tan, an accomplished web full-stack and blockchain developer with a decade of experience. My forte is developing robust, scalable web applications and forward-thinking blockchain solutions. Utilizing my skills in React.js, Vue.js, and Next.js, coupled with my proficiency in Solidity, I ensure high-quality, secure, and effective solutions tailored to your specific needs.

**Comment by SaurabhK24** [comment]
Hi Ethan, could you take a look at the issues section and see if you can make any additions to the landing UI? Please fork the repo make changes on your local branch and open a PR. Also add any comments or info you think necessary on the issue you work on. Thanks!

**Comment by kentaurse** [comment]
yh sure
thank for your reply

**Comment by kentaurse** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/86ce736c-b847-4e8a-a081-0afb152c3f0f)
plz check this
I am having trouble.
And the site is very slow.
Did you use Three.js?
